volumes:
  kafka_volume:
    name: kafka_volume
  postgres_volume:
    name: postgres_volume
services:
  mock_web_service:
    image: thepirozhkov/transfer-mock-web-service
    container_name: mock_web_service
    hostname: mockwebservice
    ports:
      - '8080:8080'
  payment_transfer_microservice:
    image: thepirozhkov/transfer-payment-microservice
    container_name: payment_transfer_microservice
    ports:
      - '9099:9099'
  deposit_microservice3:
    image: thepirozhkov/transfer-deposit-microservice
    container_name: deposit_microservice3
  deposit_microservice2:
    image: thepirozhkov/transfer-deposit-microservice
    container_name: deposit_microservice2
  deposit_microservice:
    image: thepirozhkov/transfer-deposit-microservice
    container_name: deposit_microservice
  withdrawal_microservice:
    image: thepirozhkov/transfer-withdrawal-microservice
    container_name: withdrawal_microservice
  postgres:
    hostname: postgres
    image: postgres:13.1-alpine
    container_name: postgres
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/postgresql/data/pgdata
    volumes:
      - postgres_volume:/var/postgresql/data/pgdata
  pgadmin:
    hostname: pgadmin
    image: sovchinn/pgadmin
    container_name: pgadmin
    ports:
      - '5050:5050'
  kafka_server1:
    hostname: kafka_server1
    image: bitnami/kafka:latest
    container_name: kafka_server1
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_LOG_DIRS=/tmp/server1/logs
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9091,CONTROLLER://:2181,EXTERNAL://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka_server1:9091,EXTERNAL://${HOSTNAME:-localhost}:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka_server1:2181,2@kafka_server2:2181,3@kafka_server3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka_volume:/tmp
  kafka_server2:
    hostname: kafka_server2
    image: bitnami/kafka:latest
    container_name: kafka_server2
    ports:
      - '9094:9094'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_LOG_DIRS=/tmp/server2/logs
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9091,CONTROLLER://:2181,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka_server2:9091,EXTERNAL://${HOSTNAME:-localhost}:9094
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka_server1:2181,2@kafka_server2:2181,3@kafka_server3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_KRAFT_CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka_volume:/tmp
  kafka_server3:
    hostname: kafka_server3
    image: bitnami/kafka:latest
    container_name: kafka_server3
    ports:
      - '9096:9096'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_LOG_DIRS=/tmp/server3/logs
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9091,CONTROLLER://:2181,EXTERNAL://:9096
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka_server3:9091,EXTERNAL://${HOSTNAME:-localhost}:9096
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka_server1:2181,2@kafka_server2:2181,3@kafka_server3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_KRAFT_CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka_volume:/tmp
  kafka-ui:
    depends_on:
      - 'kafka_server1'
      - 'kafka_server2'
      - 'kafka_server3'
    image: 'provectuslabs/kafka-ui'
    container_name: 'kafka-ui'
    ports:
      - '8090:8080'
    restart: 'always'
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka_server1:9091,kafka_server2:9091,kafka_server3:9091